defaults: &defaults
  machine: true
  environment:
    TERRAFORM_VERSION: 0.12.18
    KUBERGRUNT_VERSION: v0.5.8
    HELM_VERSION: v2.16.1
    HELMFILE_VERSION: v0.98.1
    KUBECONFIG: /home/circleci/.kube/config

install_gruntwork_utils: &install_gruntwork_utils
  name: install kubergrunt and terraform utils
  command: |
    curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    unzip terraform.zip
    chmod +x terraform
    sudo mv terraform /usr/local/bin/
    curl -Lo kubergrunt https://github.com/gruntwork-io/kubergrunt/releases/download/${KUBERGRUNT_VERSION}/kubergrunt_linux_amd64
    chmod +x kubergrunt 
    sudo mv kubergrunt /usr/local/bin

install_helm_client: &install_helm_client
  name: install helm client and helmfile
  command: |
    # install helm client
    curl -Lo helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz
    tar -xvf helm.tar.gz
    chmod +x linux-amd64/helm
    sudo mv linux-amd64/helm /usr/local/bin/
    curl -Lo helmfile https://github.com/roboll/helmfile/releases/download/${HELMFILE_VERSION/helmfile_linux_amd64
    chmod +x helmfile
    sudo mv helmfile /usr/local/bin

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dep-v1-{{ checksum "test/Gopkg.lock" }}

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      - save_cache:
          key: dep-v1-{{ checksum "test/Gopkg.lock" }}
          paths:
          - ./test/vendor

      # Fail the build if the pre-commit hooks don't pass. Note: if you run pre-commit install locally, these hooks will
      # execute automatically every time before you commit, ensuring the build never fails at this step!
      - run: pip install pre-commit==1.11.2
      - run: pre-commit install
      - run: pre-commit run --all-files

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - terraform

  terraform:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /home/circleci
    - checkout
    - run: echo 'export PATH=$HOME/terraform:$HOME/' >> $BASH_ENV
    - run:
        <<: *install_gruntwork_utils

    # Install helm
    - run:
        <<: *install_helm_client

    - run:
        name: update gcloud
        command: |
          sudo apt-get remove -y google-cloud-sdk
          sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
          sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
    - run:
        name: configure kubectl
        command: |
          mkdir -p ${HOME}/.kube
          touch ${HOME}/.kube/config
    - run:
        name: Authenticate and Deploy Terraform
        command: |
          mkdir -p /tmp/logs
          echo $GCLOUD_SERVICE_KEY > /home/circleci/serviceaccount.json
          export GOOGLE_APPLICATION_CREDENTIALS="/home/circleci/serviceaccount.json"
          gcloud auth activate-service-account --key-file="/home/circleci/serviceaccount.json" 
          gcloud auth application-default print-access-token
          terraform destroy -auto-approve
          terraform init
          terraform apply -auto-approve
        no_output_timeout: 12m 

     - run:
         name: checkout Helm project
         command: git clone https://github.com/johnsout/challenge-helmfile.git

     - run:
         name: deploy helmfile environments
         command: |
           cd challenge-helmfile
           helmfile -e dev apply
           helmfile -e stage apply


workflows:
  version: 2
  build-and-test:
    jobs:
    - build
    - terraform:
        requires:
        - build
